### ISSUE TITLE
Bannible / working?

### ISSUE THREAD

**Issue by Usernameistakensad** [FloopyDisk/extremefpsbooster#2]
Hey so is this still working on the latest build oif gmod?

**Comment by flleeppyy** [comment]
Most likely yes. I haven't played gmod in a long time and my reputation
around the gmod community is still bad I think. I'll check it later.

**Comment by Dimentive** [comment]
Just out of curiosity, why si your reputation in the GMod community bad?

**Comment by flleeppyy** [comment]
that was years go, I was a leaker, and did terrible shit, but I've just... forgotten about it. I was an asshole back then.
